######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 7 15:28:39 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += mainwindow.h src/codeEditor.h src/editorMode.h src/highLight.h
SOURCES += main.cpp mainwindow.cpp src/codeEditor.cpp src/highLight.cpp
RESOURCES += resources.qrc
